version: '3'

services:

  container-app:
    image: jrsaravanan/container-app
    container_name: conatiner-app
    build: ./container-app
    ports: 
      -  8080:80
    depends_on: 
      - user-app
      - details-app
   
  user-app:
   image: jrsaravanan/user-app
   container_name: user
   build: ./user-app
   ports:
    - 8081:80

  details-app:
   image: jrsaravanan/details-app
   build: ./details-app
   container_name: details
   ports:
    - 8082:80

